
  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\UI2ExitDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\WixDialogs\UI2ExitDlg.wxs

  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\UI2FatalErrorDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\WixDialogs\UI2FatalErrorDlg.wxs


  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\UI2FeaturesDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\WixDialogs\UI2FeaturesDlg.wxs

  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\UI2FilesInUseDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\WixDialogs\UI2FilesInUseDlg.wxs


  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\UI2InstallDirDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\WixDialogs\UI2InstallDirDlg.wxs

for %%. in (
"Dialogs\DatabaseServerDlg.wxs"
"Dialogs\GenericErrorDlg.wxs"
"Dialogs\UIInvalidPidDlg.wxs"
"Dialogs\UILicenseKeyDlg.wxs"
"Dialogs\WixDialogs\Common2.wxs"
"Dialogs\WixDialogs\UI2AdvancedWelcomeEulaDlg.wxs"
"Dialogs\WixDialogs\UI2BrowseDlg.wxs"
"Dialogs\WixDialogs\UI2CancelDlg.wxs"
"Dialogs\WixDialogs\UI2CustomizeDlg.wxs"
"Dialogs\WixDialogs\UI2DiskCostDlg.wxs"
"Dialogs\WixDialogs\UI2ErrorDlg.wxs"
"Dialogs\WixDialogs\UI2ExitDlg.wxs"
"Dialogs\WixDialogs\UI2FatalErrorDlg.wxs"
"Dialogs\WixDialogs\UI2FeaturesDlg.wxs"
"Dialogs\WixDialogs\UI2FilesInUseDlg.wxs"
"Dialogs\WixDialogs\UI2InstallDirDlg.wxs"
"Dialogs\WixDialogs\UI2InstallScopeDlg.wxs"
"Dialogs\WixDialogs\UI2InvalidDirDlg.wxs"
"Dialogs\WixDialogs\UI2LicenseAgreementDlg.wxs"
"Dialogs\WixDialogs\UI2MaintenanceTypeDlg.wxs"
"Dialogs\WixDialogs\UI2MaintenanceWelcomeDlg.wxs"
"Dialogs\WixDialogs\UI2MsiRMFilesInUseDlg.wxs"
"Dialogs\WixDialogs\UI2OutOfDiskDlg.wxs"
"Dialogs\WixDialogs\UI2OutOfRbDiskDlg.wxs"
"Dialogs\WixDialogs\UI2PrepareDlg.wxs"
"Dialogs\WixDialogs\UI2ProgressDlg.wxs"
"Dialogs\WixDialogs\UI2ResumeDlg.wxs"
"Dialogs\WixDialogs\UI2SetupTypeDlg.wxs"
"Dialogs\WixDialogs\UI2UserExitDlg.wxs"
"Dialogs\WixDialogs\UI2VerifyReadyDlg.wxs"
"Dialogs\WixDialogs\UI2WaitForCostingDlg.wxs"
"Dialogs\WixDialogs\UI2WelcomeDlg.wxs"
"Dialogs\WixDialogs\UI2WelcomeEulaDlg.wxs"
"Dialogs\WixDialogs\UI3LauntExitDlg.wxs"
"Dialogs\WixDialogs\WixUI2_Advanced.wxs"
"Dialogs\WixDialogs\WixUI2_FeatureTree.wxs"
"Dialogs\WixDialogs\WixUI2_InstallDir.wxs"
"Dialogs\WixDialogs\WixUI2_Minimal.wxs"
"Dialogs\WixDialogs\WixUI2_Mondo.wxs"
"Dialogs\WixDialogs\WixUI3_Mondo.wxs"
) do echo %%. && call   c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\UI2ExitDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll "%%."


  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\UI2InstallScopeDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\WixDialogs\UI2InstallScopeDlg.wxs

  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\UI2InvalidDirDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\WixDialogs\UI2InvalidDirDlg.wxs


  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\DatabaseServerDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\DatabaseServerDlg.wxs

C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup>msbuild.exe /property:WixTasksPath=c:\wix\WixTasks.dll /property:WixCATargetsPath=c:\wix\SDK\wix.ca.targets /property:WixTargetsPath=c:\wix\wix.targets /property:WixTasksPath=c:\wix\WixTasks.dll /property:WixToolPath=c:\wix WixDataBase.Setup.wixproj 
Microsoft (R) Build Engine version 4.0.30319.17929
[Microsoft .NET Framework, version 4.0.30319.18063]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/28/2014 7:21:13 PM.
Project "C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj" on node 1 (default targets).
Project "C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj" (1) is building "C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj" (2) on node 1 (default targets).
CoreResGen:
  No resources are out of date with respect to their source files. Skipping resource generation.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
PackCustomAction:
Skipping target "PackCustomAction" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  WixDataBase.CustomAction -> C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll
Done Building Project "C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj" (default targets).
ResolveWixExtensionReferences:
  WixReference: WixUtilExtension
  Trying {HintPathFromItem}
  Trying path \WixUtilExtension.dll
  Trying {RawFileName}
  Trying path WixUtilExtension
  Trying path WixUtilExtension.dll
  Trying c:\wix
  Trying path c:\wix\WixUtilExtension
  Trying path c:\wix\WixUtilExtension.dll
  Resolved path c:\wix\WixUtilExtension.dll
  WixReference: WixUIExtension
  Trying {HintPathFromItem}
  Trying path \WixUIExtension.dll
  Trying {RawFileName}
  Trying path WixUIExtension
  Trying path WixUIExtension.dll
  Trying c:\wix
  Trying path c:\wix\WixUIExtension
  Trying path c:\wix\WixUIExtension.dll
  Resolved path c:\wix\WixUIExtension.dll
  WixReference: WixNetFxExtension
  Trying {HintPathFromItem}
  Trying path \WixNetFxExtension.dll
  Trying {RawFileName}
  Trying path WixNetFxExtension
  Trying path WixNetFxExtension.dll
  Trying c:\wix
  Trying path c:\wix\WixNetFxExtension
  Trying path c:\wix\WixNetFxExtension.dll
  Resolved path c:\wix\WixNetFxExtension.dll
c:\wix\wix.targets(1093,5): warning : Solution properties are only available during IDE builds or when building the solution file from the command line. To turn off this warning set <DefineSolutionProperties>false</DefineSolutionProperties> in your .wixproj file. [C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj]
Compile:
Skipping target "Compile" because all output files are up-to-date with respect to the input files.
Compile:
  c:\wix\candle.exe -dDebug -d"DevEnvDir=*Undefined if not building from within Visual Studio*" -d"SolutionDir=*Undefined if not building a solution or within Visual Studio*" -d"SolutionExt=*Undefined if not building a solution or within Visual Studio*" -d"SolutionFileName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionName=*Undefined if not building a solution or within Visual Studio*" -d"SolutionPath=*Undefined if not building a solution or within Visual Studio*" -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\ -dProjectExt=.wixproj -dProjectFileName=WixDataBase.Setup.wixproj -dProjectName=WixDataBase.Setup -dProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\WixDataBase.Setup.wixproj -dTargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\ -dTargetExt=.msi -dTargetFileName=WixDataBase.Setup.msi -dTargetName=WixDataBase.Setup -dTargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup\bin\Debug\WixDataBase.Setup.msi -dWixDataBase.CustomAction.Configuration= -dWixDataBase.CustomAction.FullConfiguration= -dWixDataBase.CustomAction.Platform= -dWixDataBase.CustomAction.ProjectDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\ -dWixDataBase.CustomAction.ProjectExt=.csproj -dWixDataBase.CustomAction.ProjectFileName=WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.ProjectName=WixDataBase.CustomAction -dWixDataBase.CustomAction.ProjectPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\WixDataBase.CustomAction.csproj -dWixDataBase.CustomAction.TargetDir=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\ -dWixDataBase.CustomAction.TargetExt=.dll -dWixDataBase.CustomAction.TargetFileName=WixDataBase.CustomAction.dll -dWixDataBase.CustomAction.TargetName=WixDataBase.CustomAction -dWixDataBase.CustomAction.TargetPath=C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.CustomAction\bin\Debug\WixDataBase.CustomAction.dll -out obj\Debug\GenericErrorDlg.wixobj -arch x86 -ext c:\wix\WixUtilExtension.dll -ext c:\wix\WixUIExtension.dll -ext c:\wix\WixNetFxExtension.dll Dialogs\GenericErrorDlg.wxs
  Could not load file or assembly 'file:///c:\wix\candle.exe' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
     at System.Reflection.Assembly.LoadFrom(String assemblyFile)
     at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(Object parameters)

C:\developer\sergueik\csharp\WixTutor\Fuente\WixDataBase.Setup\WixDataBase.Setup>REM WixDataBase.Setup.sln  
